export const CLIENT_MESSAGES = {
  JOIN_CHANNEL: 'JOIN_CHANNEL',
  LEAVE_CHANNEL: 'LEAVE_CHANNEL',
  SEND_MESSAGE: 'SEND_MESSAGE',
  TYPING_START: 'TYPING_START',
};
export const SERVER_MESSAGES = {
  NEW_MESSAGE: 'NEW_MESSAGE',
  JOINED: 'JOINED',
  PRESENCE_UPDATE: 'PRESENCE_UPDATE',
  TYPING_UPDATE: 'TYPING_UPDATE',
  ERROR: 'ERROR',
};